language: node_js
node_js:
  - "node"
jobs:
  include:
    - stage: release
      script:
        - npm install gulp -g
        - if [[ $TRAVIS_BRANCH == "master" ]] && [[ $TRAVIS_COMMIT_MESSAGE != Release* ]]; chmod +x ./prepare-git.sh && bash ./prepare-git.sh && gulp release-ci; fi;
    - stage: publish
      script:
        - npm install gulp -g
        - if [[ $TRAVIS_TAG ]]; then gulp publish-ci; fi;
