language: node_js
node_js:
  - "node"
jobs:
  include:
    - stage: build
      script:
        - chmod +x ./build.sh
        - bash ./build.sh
    - stage: test
      script:
        - chmod +x ./test.sh
        - bash ./test.sh
    - stage: release
      script:
        - chmod +x ./release.sh
        - if [ "$TRAVIS_BRANCH" == "master" ]; then bash ./release.sh; fi;
    - stage: publish
      script:
        - chmod +x ./publish.sh
        - if [ "$TRAVIS_TAG" ]; then bash ./publish.sh; fi;
