language: node_js
node_js:
  - "node"
jobs:
  include:
    - stage: build
      script:
        - npm install gulp -g
        - gulp build
    - stage: release
      script:
        - npm install gulp -g
        - chmod +x ./release.sh
        - if [ "$TRAVIS_BRANCH" == "master" ]; then bash ./release.sh; fi;
    - stage: publish
      script:
        - npm install gulp -g
        - chmod +x ./publish.sh
        - if [ "$TRAVIS_TAG" ]; then bash ./publish.sh; fi;
