language: node_js
node_js:
  - "node"
jobs:
  include:
    - stage: release
      script:
        - npm install gulp -g
        - if [[ $TRAVIS_BRANCH == "master" ]] && [[ $TRAVIS_COMMIT_MESSAGE != Release* ]]; then gulp release-ci; fi;
    - stage: publish
      script:
        - npm install gulp -g
        - chmod +x ./publish.sh
        - if [[ $TRAVIS_TAG ]]; then bash ./publish.sh; fi;
